  INFO root [2018-05-20 11:20:56,287] - 
  INFO root [2018-05-20 11:20:56,388] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:20:57,768] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:20:57,769] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:20:57,770] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:20:58,313] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49752 )
  INFO root [2018-05-20 11:20:58,314] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49752, SOMAXCONN=5.
  INFO root [2018-05-20 11:20:58,315] - server-configs:
  INFO root [2018-05-20 11:20:58,316] - 	internalAddr : 192.168.0.104:49752
  INFO root [2018-05-20 11:20:58,316] - 	componentID : 4000
  INFO root [2018-05-20 11:21:00,002] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 27066. PID: 2820 ----
  INFO root [2018-05-20 11:21:00,004] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:21:00,019] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:21:00,020] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:21:03,848] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:04,058] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:04,170] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:05,023] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:05,088] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:05,168] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:05,344] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:06,267] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:09,597] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:21:09,598] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:21:12,118] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:21:12,120] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:21:12,198] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:21:12,259] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:21:12,809] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
E53B42DE45E5E8483EDA5074CD14ECEF7ADA22F159B630843CDB7057AD3A57F0A24557C5B997D711212F0BA9D84185D06C9ED754D2DD0E20E480A7BE557AC4DC3AA1191C7220D29123399A5C734628C2CBA424100C3B9F409FF45AD93EEFA24A30E1EB1935407D6A829044534C2D8105C896D719341BB68636A26A38B4FE30D4
 DEBUG root [2018-05-20 11:21:13,972] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-05-20 11:21:16,108] - DBInterfaceMysql::attach: mysql_errno=2003, mysql_error=Can't connect to MySQL server on 'localhost' (10061)
 ERROR root [2018-05-20 11:21:16,110] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x23f1b0
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-05-20 11:21:16,111] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-05-20 11:21:16,143] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 3.99 seconds
 ERROR root [2018-05-20 11:21:16,143] - app::initialize(): initialization failed!
 DEBUG root [2018-05-20 11:21:16,145] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-05-20 11:21:16,546] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:21:16,546] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:16,547] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:16,547] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:16,548] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:16,548] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:16,548] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:16,549] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:16,549] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:16,579] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:21:16,580] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-20 11:21:16,880] - ThreadPool::destroy(): waiting for thread(2)[0x2f41b8,0x2f4150,], try=1
 DEBUG root [2018-05-20 11:21:17,280] - TPThread::~TPThread(): 0x2f41b8
 DEBUG root [2018-05-20 11:21:17,281] - TPThread::~TPThread(): 0x2f4150
 DEBUG root [2018-05-20 11:21:17,282] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:21:17,283] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:21:17,283] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:21:17,284] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:17,285] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:21:17,285] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:21:17,285] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:17,286] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:17,286] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-05-20 11:21:24,183] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-05-20 11:21:29,991] - 
  INFO root [2018-05-20 11:21:29,991] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:21:29,992] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:21:29,992] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:21:29,992] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:21:30,007] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49771 )
  INFO root [2018-05-20 11:21:30,007] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49771, SOMAXCONN=5.
  INFO root [2018-05-20 11:21:30,007] - server-configs:
  INFO root [2018-05-20 11:21:30,007] - 	internalAddr : 192.168.0.104:49771
  INFO root [2018-05-20 11:21:30,007] - 	componentID : 4000
  INFO root [2018-05-20 11:21:31,526] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 27232. PID: 1124 ----
  INFO root [2018-05-20 11:21:31,527] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:21:31,528] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:21:31,529] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:21:31,688] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:31,688] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:31,689] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:31,691] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:31,692] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:31,692] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:31,692] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:31,721] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:31,749] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:21:31,749] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:21:31,759] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:21:31,759] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:21:31,760] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:21:31,760] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:21:32,077] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
12C3272E2DDC8C0E9A805D4BC1230422AB326F45601FA7DC4CE5AF49DF1DC3E9B1660C5A03A74FBB1AF1478F7182217245D4F74B9B60BBDE5F7476CA5EE8EC4C106BF786095BC8282F1253B2495459BBD9A7B2AF49A8C7560B8D234889DFB626DA76E69BBE1E0576773D9FC9F39058229778DBAA0CB392E7EC6534ED4C6CEA1C
 DEBUG root [2018-05-20 11:21:32,079] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-05-20 11:21:34,080] - DBInterfaceMysql::attach: mysql_errno=2003, mysql_error=Can't connect to MySQL server on 'localhost' (10061)
 ERROR root [2018-05-20 11:21:34,082] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x2aeeb0
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-05-20 11:21:34,083] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-05-20 11:21:34,086] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 2.33 seconds
 ERROR root [2018-05-20 11:21:34,087] - app::initialize(): initialization failed!
 DEBUG root [2018-05-20 11:21:34,088] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-05-20 11:21:34,489] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:21:34,489] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:21:34,490] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:21:34,490] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:21:34,491] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:21:34,491] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:21:34,491] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:21:34,492] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:21:34,492] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:21:34,523] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:21:34,523] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-20 11:21:34,823] - ThreadPool::destroy(): waiting for thread(2)[0x3341b8,0x334150,], try=1
 DEBUG root [2018-05-20 11:21:35,223] - TPThread::~TPThread(): 0x3341b8
 DEBUG root [2018-05-20 11:21:35,223] - TPThread::~TPThread(): 0x334150
 DEBUG root [2018-05-20 11:21:35,224] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:21:35,224] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:21:35,225] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:21:35,225] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:35,225] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:21:35,225] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:21:35,226] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:35,226] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:21:35,226] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-05-20 11:21:42,027] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-05-20 11:22:03,524] - 
  INFO root [2018-05-20 11:22:03,525] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:22:03,526] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:22:03,526] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:22:03,526] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:22:03,546] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49795 )
  INFO root [2018-05-20 11:22:03,546] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49795, SOMAXCONN=5.
  INFO root [2018-05-20 11:22:03,546] - server-configs:
  INFO root [2018-05-20 11:22:03,546] - 	internalAddr : 192.168.0.104:49795
  INFO root [2018-05-20 11:22:03,546] - 	componentID : 4000
  INFO root [2018-05-20 11:22:05,056] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 27343. PID: 972 ----
  INFO root [2018-05-20 11:22:05,057] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:22:05,057] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:22:05,058] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:22:05,221] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:22:05,221] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:22:05,221] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:22:05,224] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:22:05,224] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:22:05,225] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:22:05,225] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:22:05,252] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:22:05,279] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:22:05,279] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:22:05,290] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:22:05,290] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:22:05,290] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:22:05,290] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:22:05,586] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
119AD3840EEE72F81286C9D2F60CB08D2EDB114852087555E5912AA3FB5BF950403B0B89BB2A67BD3C62E7F6E5F8DF330A925E158E87AF1B384E59EAD95A324DD0614C7E86C91738E65CFA95CA3373839C10F9DEAE7DD32000E14D574E0CA1C2930FCBF47DD3B929868459415E0895DC8F4BEF24FE60D126DFEFCD2ED412AD79
 DEBUG root [2018-05-20 11:22:05,587] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-05-20 11:22:07,588] - DBInterfaceMysql::attach: mysql_errno=2003, mysql_error=Can't connect to MySQL server on 'localhost' (10061)
 ERROR root [2018-05-20 11:22:07,590] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x23f184
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-05-20 11:22:07,591] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-05-20 11:22:07,593] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 2.30 seconds
 ERROR root [2018-05-20 11:22:07,594] - app::initialize(): initialization failed!
 DEBUG root [2018-05-20 11:22:07,596] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-05-20 11:22:07,996] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:22:07,996] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:22:07,997] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:22:07,997] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:22:07,998] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:22:07,998] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:22:07,998] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:22:07,999] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:22:07,999] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:22:08,029] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:22:08,030] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-20 11:22:08,330] - ThreadPool::destroy(): waiting for thread(2)[0x3b41b8,0x3b4150,], try=1
 DEBUG root [2018-05-20 11:22:08,731] - TPThread::~TPThread(): 0x3b41b8
 DEBUG root [2018-05-20 11:22:08,731] - TPThread::~TPThread(): 0x3b4150
 DEBUG root [2018-05-20 11:22:08,732] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:22:08,733] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:22:08,733] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:22:08,734] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:22:08,735] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:22:08,735] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:22:08,736] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:22:08,736] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:22:08,736] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-05-20 11:22:15,537] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-05-20 11:23:32,110] - 
  INFO root [2018-05-20 11:23:32,111] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:23:32,111] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:23:32,111] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:23:32,112] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:23:32,119] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49851 )
  INFO root [2018-05-20 11:23:32,119] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49851, SOMAXCONN=5.
  INFO root [2018-05-20 11:23:32,119] - server-configs:
  INFO root [2018-05-20 11:23:32,119] - 	internalAddr : 192.168.0.104:49851
  INFO root [2018-05-20 11:23:32,119] - 	componentID : 4000
  INFO root [2018-05-20 11:23:33,627] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 27634. PID: 3400 ----
  INFO root [2018-05-20 11:23:33,628] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:23:33,628] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:23:33,629] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:23:33,787] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:23:33,787] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:23:33,788] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:23:33,791] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:23:33,791] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:23:33,791] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:23:33,792] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:23:33,822] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:23:33,852] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:23:33,852] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:23:33,863] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:23:33,863] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:23:33,863] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:23:33,863] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:23:34,163] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
63A3330A2650C1BB4F2A3ACDA3A99137B162E69E98EC1282D996A08E56C5C7DF698E17D2EDE1CF034F5A26EFA066F58F7D3FF93F004B5E277EC348B12EC97A424877BD793BD2641BD65ED53448400E082EC0DF42794421DFAEACE527B371901D25955026E1151A3D11390603E366BFFD3B4F0ECECF94291912D8A52AE750CC6E
 DEBUG root [2018-05-20 11:23:34,164] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-05-20 11:23:36,158] - DBInterfaceMysql::attach: mysql_errno=2003, mysql_error=Can't connect to MySQL server on 'localhost' (10061)
 ERROR root [2018-05-20 11:23:36,159] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x30f220
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-05-20 11:23:36,160] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-05-20 11:23:36,161] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 2.30 seconds
 ERROR root [2018-05-20 11:23:36,161] - app::initialize(): initialization failed!
 DEBUG root [2018-05-20 11:23:36,162] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-05-20 11:23:36,562] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:23:36,563] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:23:36,563] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:23:36,564] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:23:36,564] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:23:36,565] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:23:36,565] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:23:36,565] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:23:36,566] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:23:36,597] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:23:36,597] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-20 11:23:36,897] - ThreadPool::destroy(): waiting for thread(2)[0x7a41b8,0x7a4150,], try=1
 DEBUG root [2018-05-20 11:23:37,298] - TPThread::~TPThread(): 0x7a41b8
 DEBUG root [2018-05-20 11:23:37,298] - TPThread::~TPThread(): 0x7a4150
 DEBUG root [2018-05-20 11:23:37,298] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:23:37,298] - Bundle::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:23:37,298] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:23:37,299] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:23:37,299] - UDPPacket::destroyObjPool(): size 14.
 DEBUG root [2018-05-20 11:23:37,299] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:23:37,299] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:23:37,299] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:23:37,299] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-05-20 11:23:44,099] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-05-20 11:24:43,971] - 
  INFO root [2018-05-20 11:24:43,973] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:24:43,973] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:24:43,973] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:24:43,973] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:24:43,977] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49894 )
  INFO root [2018-05-20 11:24:43,977] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49894, SOMAXCONN=5.
  INFO root [2018-05-20 11:24:43,977] - server-configs:
  INFO root [2018-05-20 11:24:43,977] - 	internalAddr : 192.168.0.104:49894
  INFO root [2018-05-20 11:24:43,977] - 	componentID : 4000
  WARN root [2018-05-20 11:24:44,289] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20881, errorno=10048
  INFO root [2018-05-20 11:24:44,293] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 27866. PID: 3380 ----
  INFO root [2018-05-20 11:24:44,293] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:24:44,293] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:24:44,293] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:24:44,419] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:24:44,419] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:24:44,420] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:24:44,423] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:24:44,423] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:24:44,423] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:24:44,423] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:24:44,450] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:24:44,477] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:24:44,477] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:24:44,487] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:24:44,488] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:24:44,488] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:24:44,488] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:24:44,754] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
685EF94273609A57C4ED5FA2175AA77452B0F3130B8E8A227386E03D7CED29D4FFCCC7518A0303641DF9F61B3C3CE99B925D52B87AB8FFC40C01D90CE0C91DF2BD03DF3369A73A4371F3AE33BD4A2DEC46A642BD738AD7BE0857045FBE671ACA552AA4503B59BB6AA02C741F396D4A1B47D12DF87A07DA00B2C8C34E6BFC1109
 DEBUG root [2018-05-20 11:24:44,756] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 ERROR root [2018-05-20 11:24:46,757] - DBInterfaceMysql::attach: mysql_errno=2003, mysql_error=Can't connect to MySQL server on 'localhost' (10061)
 ERROR root [2018-05-20 11:24:46,759] - DBUtil::createInterface: attach to database failed!
	dbinterface=0x2ef494
	args=interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=no.

 ERROR root [2018-05-20 11:24:46,760] - Dbmgr::initDB(): can't create dbInterface!
  WARN root [2018-05-20 11:24:46,763] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 2.28 seconds
 ERROR root [2018-05-20 11:24:46,763] - app::initialize(): initialization failed!
 DEBUG root [2018-05-20 11:24:46,765] - ThreadPool::destroy(): starting size 0.
 DEBUG root [2018-05-20 11:24:47,166] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:24:47,167] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:24:47,167] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:24:47,168] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:24:47,168] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:24:47,169] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:24:47,169] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:24:47,169] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:24:47,170] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:24:47,194] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-20 11:24:47,194] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-20 11:24:47,494] - ThreadPool::destroy(): waiting for thread(2)[0x5e4220,0x5e41b8,], try=1
 DEBUG root [2018-05-20 11:24:47,894] - TPThread::~TPThread(): 0x5e4220
 DEBUG root [2018-05-20 11:24:47,894] - TPThread::~TPThread(): 0x5e41b8
 DEBUG root [2018-05-20 11:24:47,894] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-05-20 11:24:47,894] - Bundle::destroyObjPool(): size 13.
 DEBUG root [2018-05-20 11:24:47,895] - Channel::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:24:47,895] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:24:47,895] - UDPPacket::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:24:47,895] - EndPoint::destroyObjPool(): size 15.
 DEBUG root [2018-05-20 11:24:47,896] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:24:47,896] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-05-20 11:24:47,896] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-05-20 11:24:54,696] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2018-05-20 11:25:40,327] - 
  INFO root [2018-05-20 11:25:40,327] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:25:40,328] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:25:40,328] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:25:40,328] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:25:40,334] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49930 )
  INFO root [2018-05-20 11:25:40,334] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49930, SOMAXCONN=5.
  INFO root [2018-05-20 11:25:40,334] - server-configs:
  INFO root [2018-05-20 11:25:40,334] - 	internalAddr : 192.168.0.104:49930
  INFO root [2018-05-20 11:25:40,334] - 	componentID : 4000
  INFO root [2018-05-20 11:25:41,840] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 28052. PID: 2140 ----
  INFO root [2018-05-20 11:25:41,841] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:25:41,842] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:25:41,842] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:25:41,983] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:25:41,984] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:25:41,984] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:25:41,987] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:25:41,987] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:25:41,988] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:25:41,988] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:25:42,016] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:25:42,044] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:25:42,044] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:25:42,054] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:25:42,054] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:25:42,054] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:25:42,055] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:25:42,347] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
7A35B4FF925AFC2A1B6C19A3BEBAFD7530BD4E73F67135E691334704AC690D8AA79AF279E2BEF4849946AA71B879AFFC789BDBC5CB51F2A88F09B3C7243D4B1EB5D2284A325937D64C59A22DF3FE5B63B0B7EB12A16EC08D090B98FC1761570805290165CFB3C8CF89F8B467CF79D14402A71B5119CFEC330F6B48FB8497C297
 DEBUG root [2018-05-20 11:25:42,348] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:25:42,535] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2018-05-20 11:25:42,535] - DBUtil::createInterface[0x3beda0]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2018-05-20 11:25:42,554] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2018-05-20 11:25:42,554] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:25:42,554] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2018-05-20 11:25:42,554] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2018-05-20 11:25:42,554] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:25:42,555] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:25:42,555] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:25:42,556] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:25:42,556] - DBThread::onStart(): 0x8881c8!
 DEBUG root [2018-05-20 11:25:42,556] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:25:42,556] - DBThread::onStart(): 0x8883e8!
 DEBUG root [2018-05-20 11:25:42,556] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:25:42,556] - DBThread::onStart(): 0x888250!
 DEBUG root [2018-05-20 11:25:42,556] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:25:42,557] - DBThread::onStart(): 0x888360!
 DEBUG root [2018-05-20 11:25:42,557] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:25:42,557] - DBThread::onStart(): 0x8882d8!
  INFO root [2018-05-20 11:25:42,694] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:42,699] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:42,802] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:42,859] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:42,900] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:42,934] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:43,143] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:43,145] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:43,145] - DBInterfaceMysql::query: successfully!
  WARN root [2018-05-20 11:25:43,230] - DBTask::process(): took 0.45 seconds
sql:(delete from kbe_email_verification where logtime<1526783143 and type=3)
  WARN root [2018-05-20 11:25:43,234] - DBTask::process(): took 0.37 seconds
sql:(show index from tbl_Account)
  WARN root [2018-05-20 11:25:43,256] - DBTask::process(): took 0.56 seconds
sql:(insert into kbe_serverlog (heartbeatTime, logger) values(1526786742,4000) ON DUPLICATE KEY UPDATE heartbeatTime=1526786742)
  INFO root [2018-05-20 11:25:43,403] - DBInterfaceMysql::query: successfully!
  WARN root [2018-05-20 11:25:43,403] - DBTask::process(): took 0.70 seconds
sql:(delete from kbe_entitylog where logger in (4000))
 DEBUG root [2018-05-20 11:25:43,897] - syncToDB(): Halls->sm_autoLoad(tinyint not null DEFAULT 0).
 DEBUG root [2018-05-20 11:25:43,898] - syncToDB(): Room->sm_autoLoad(tinyint not null DEFAULT 0).
  INFO root [2018-05-20 11:25:44,740] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:25:44,741] - DBInterfaceMysql::query: successfully!
  WARN root [2018-05-20 11:25:44,743] - DBTask::process(): took 1.85 seconds
sql:(show index from tbl_Halls)
  WARN root [2018-05-20 11:25:44,744] - DBTask::process(): took 1.51 seconds
sql:(show index from tbl_Room)
  WARN root [2018-05-20 11:25:44,761] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 2.71 seconds
  INFO root [2018-05-20 11:25:45,123] - ---- dbmgr is running ----
 DEBUG root [2018-05-20 11:25:45,123] - Components::process(): Request for the process of identity...
  WARN root [2018-05-20 11:25:45,434] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20201, errorno=10048
  INFO root [2018-05-20 11:25:52,256] - ServerApp::onRegisterNewApp: uid:28052, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.104, intport:49929, extaddr:nonsupport, extport:0,  from 192.168.0.104:49950/0/0/0.
  INFO root [2018-05-20 11:25:52,257] - Components::addComponent: reset orderLog, uid=28052!
  INFO root [2018-05-20 11:25:52,258] - Components::addComponent[baseappmgr], uid=28052, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:25:52,615] - Components::findComponents: find logger(1)...
  INFO root [2018-05-20 11:25:52,625] - Components::findComponents: found logger, addr:192.168.0.104:49928
  INFO root [2018-05-20 11:25:52,626] - Components::addComponent[logger], uid=28052, componentID=2000, globalorderid=2, grouporderid=1, totalcount=1
  INFO root [2018-05-20 11:25:52,633] - Components::process(): Found all the components!
  WARN root [2018-05-20 11:25:52,634] - Forwarding logs to logger[192.168.0.104:49928/0/0/0]...
 ERROR root [2018-05-20 11:26:07,784] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:26:07,785] - The following logs sent to logger failed:
  WARN root [2018-05-20 11:26:07,786] - ==> [2018-05-20 11:26:07 783] TCPPacketReceiver::processPendingEvents(192.168.0.104:49928): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-20 11:26:07,786] - ==> [2018-05-20 11:26:07 785] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-20 11:26:08,851] - 
  INFO root [2018-05-20 11:26:08,852] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-20 11:26:08,852] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-20 11:26:08,852] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-20 11:26:08,852] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-20 11:26:08,857] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.104 ( 192.168.0.104:49968 )
  INFO root [2018-05-20 11:26:08,857] - NetworkInterface::initialize(INTERNAL): address 192.168.0.104:49968, SOMAXCONN=5.
  INFO root [2018-05-20 11:26:08,857] - server-configs:
  INFO root [2018-05-20 11:26:08,857] - 	internalAddr : 192.168.0.104:49968
  INFO root [2018-05-20 11:26:08,857] - 	componentID : 4000
  WARN root [2018-05-20 11:26:09,168] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20151, errorno=10048
  INFO root [2018-05-20 11:26:09,172] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 28143. PID: 6016 ----
  INFO root [2018-05-20 11:26:09,172] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-20 11:26:09,172] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-20 11:26:09,173] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-20 11:26:09,299] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-20 11:26:09,300] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-20 11:26:09,300] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-20 11:26:09,303] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-20 11:26:09,303] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-20 11:26:09,303] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-20 11:26:09,304] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-20 11:26:09,329] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-20 11:26:09,355] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-20 11:26:09,356] - Script::install(): KBExtra is successfully!
  INFO root [2018-05-20 11:26:09,366] - Dbmgr::initializeEnd: digest(F7398DD01F5FC8D787D90C5312DB1BF0)
S_INFO root [2018-05-20 11:26:09,366] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-20 11:26:09,366] - TelnetServer server is running on port 32000
  INFO root [2018-05-20 11:26:09,367] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-05-20 11:26:09,639] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
E3E05B968BCAE4BB04F57068FF88F50CBC04364E3FB61D44FE19575CD295ADD12B506CBB1292AEA43130A712871A5122FFD705330A486668ECD329A4EC5A8E473081426CBF14F87780B3F4B9907A1E2B03796E5652D32E21FDFD2A3ADB6023D1967876D76211A48131BFB30CE25D8532E9823D411D33344A6C75EFBEB06E0378
 DEBUG root [2018-05-20 11:26:09,640] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:26:09,642] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2018-05-20 11:26:09,642] - DBUtil::createInterface[0x171f35c]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2018-05-20 11:26:09,643] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2018-05-20 11:26:09,643] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:26:09,643] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2018-05-20 11:26:09,643] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2018-05-20 11:26:09,643] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:26:09,644] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:26:09,644] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-05-20 11:26:09,644] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:26:09,645] - DBThread::onStart(): 0x1b7db20!
 DEBUG root [2018-05-20 11:26:09,645] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:26:09,645] - DBThread::onStart(): 0x1b7da98!
 DEBUG root [2018-05-20 11:26:09,645] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:26:09,645] - DBThread::onStart(): 0x1b7dba8!
 DEBUG root [2018-05-20 11:26:09,645] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:26:09,646] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-05-20 11:26:09,646] - DBThread::onStart(): 0x1b7dcb8!
 DEBUG root [2018-05-20 11:26:09,646] - DBThread::onStart(): 0x1b7dc30!
  INFO root [2018-05-20 11:26:09,747] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,752] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,755] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,755] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,756] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,756] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,757] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,757] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,758] - DBInterfaceMysql::query: successfully!
  INFO root [2018-05-20 11:26:09,759] - DBInterfaceMysql::query: successfully!
  WARN root [2018-05-20 11:26:09,804] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 0.44 seconds
  INFO root [2018-05-20 11:26:10,122] - ---- dbmgr is running ----
 DEBUG root [2018-05-20 11:26:10,123] - Components::process(): Request for the process of identity...
