  INFO root [2018-04-29 15:56:12,245] - 
  INFO root [2018-04-29 15:56:12,270] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-29 15:56:12,294] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-04-29 15:56:12,294] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-04-29 15:56:12,295] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-04-29 15:56:12,306] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:51795 )
  INFO root [2018-04-29 15:56:12,306] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:51795, SOMAXCONN=5.
  INFO root [2018-04-29 15:56:12,306] - server-configs:
  INFO root [2018-04-29 15:56:12,306] - 	internalAddr : 192.168.0.106:51795
  INFO root [2018-04-29 15:56:12,306] - 	componentID : 4000
  WARN root [2018-04-29 15:56:12,617] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20906, errorno=10048
  INFO root [2018-04-29 15:56:12,620] - ---- dbmgr Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F28F1C37BCC70CD27B77841D4A30E3D7. Config: Debug X86. Built: 15:52:44 Apr 29 2018. AppID: 4000. UID: 21461. PID: 21236 ----
  INFO root [2018-04-29 15:56:12,620] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-04-29 15:56:12,621] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-29 15:56:12,621] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-29 15:56:12,772] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-29 15:56:12,772] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-29 15:56:12,773] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-29 15:56:12,776] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-29 15:56:12,776] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-29 15:56:12,776] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-29 15:56:12,777] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-29 15:56:13,141] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-29 15:56:13,467] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:52:37) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-04-29 15:56:13,467] - Script::install(): KBExtra is successfully!
  INFO root [2018-04-29 15:56:13,523] - Dbmgr::initializeEnd: digest(363BB7D9C7C9010E5779213C13D38542)
S_INFO root [2018-04-29 15:56:13,523] - onDBMgrReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-29 15:56:13,523] - TelnetServer server is running on port 32000
  INFO root [2018-04-29 15:56:13,524] - Dbmgr::initInterfacesHandler: interfaces addr(127.0.0.1:30099), accountType:(interfaces), chargeType:(interfaces).
  WARN root [2018-04-29 15:56:13,808] - DBUtil::initialize: db(default) password is not encrypted!
please use password(rsa):
210DB3A75AE1AE57B50A231DC440228448D5D514E177F638496E41236F8856ACD32615481AF15ED143128320C487CB87000064565F108AF9CFAF3A6228FEF1D06BC0584A885DC65EE3D618F0A6453E95C7618498731FE106E5DFB18DE34868AFD02BE539BB29AF3084B19BA4C0921ABFAF2825DC7B50DD739D4E515D751A49D6
 DEBUG root [2018-04-29 15:56:13,877] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-04-29 15:56:14,146] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
  INFO root [2018-04-29 15:56:14,146] - DBUtil::createInterface[0x18ded64]: interface=default, dbtype=mysql, ip=localhost, port=3306, currdatabase=kbe, username=kbe, connected=yes.

  INFO root [2018-04-29 15:56:14,146] - ThreadPool::createThreadPool: creating  threadpool...
 DEBUG root [2018-04-29 15:56:14,147] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
  INFO root [2018-04-29 15:56:14,147] - ThreadPool::createThreadPool: successfully(5), newThreadCount=5, normalMaxThreadCount=5, maxThreadCount=5
 DEBUG root [2018-04-29 15:56:14,147] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-04-29 15:56:14,147] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-04-29 15:56:14,147] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-04-29 15:56:14,148] - DBInterfaceMysql::attach: connect: localhost:3306 starting...
 DEBUG root [2018-04-29 15:56:14,149] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-04-29 15:56:14,149] - DBThread::onStart(): 0x1d27f50!
 DEBUG root [2018-04-29 15:56:14,149] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-04-29 15:56:14,150] - DBThread::onStart(): 0x1d27ec8!
 DEBUG root [2018-04-29 15:56:14,150] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-04-29 15:56:14,150] - DBThread::onStart(): 0x1d27fd8!
 DEBUG root [2018-04-29 15:56:14,151] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-04-29 15:56:14,151] - DBThread::onStart(): 0x1d28060!
 DEBUG root [2018-04-29 15:56:14,153] - DBInterfaceMysql::attach: successfully! addr: localhost:3306
 DEBUG root [2018-04-29 15:56:14,153] - DBThread::onStart(): 0x1d280e8!
  INFO root [2018-04-29 15:56:14,490] - DBInterfaceMysql::query: successfully!
  INFO root [2018-04-29 15:56:14,492] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:14,492] - DBInterfaceMysql::checkErrors: not found Account table, reset kbe_* table...
  WARN root [2018-04-29 15:56:15,143] - DBInterfaceMysql::checkErrors: reset kbe_* table end!
  INFO root [2018-04-29 15:56:15,189] - DBInterfaceMysql::query: successfully!
  INFO root [2018-04-29 15:56:15,696] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:15,697] - DBTask::process(): took 0.55 seconds
sql:(CREATE TABLE IF NOT EXISTS kbe_accountinfos (`accountName` varchar(128) not null, PRIMARY KEY idKey (`accountName`),`password` varchar(255),`bindata` blob,`email` varchar(191) not null, UNIQUE KEY `email` (`email`),`entityDBID` bigint(20) unsigned not null DEFAULT 0, UNIQUE KEY `entityDBID` (`entityDBID`),`flags` int unsigned not null DEFAULT 0,`deadline` bigint(20) not null DEFAULT 0,`regtime` bigint(20) not null DEFAULT 0,`lasttime` bigint(20) not null DEFAULT 0,`numlogin` int unsigned not null DEFAULT 0)ENGINE=InnoDB)
  INFO root [2018-04-29 15:56:15,738] - DBInterfaceMysql::query: successfully!
  INFO root [2018-04-29 15:56:15,963] - DBInterfaceMysql::query: successfully!
 DEBUG root [2018-04-29 15:56:15,964] - syncToDB(): Account->sm_autoLoad(tinyint not null DEFAULT 0).
  WARN root [2018-04-29 15:56:15,993] - DBTask::process(): took 0.85 seconds
sql:(insert into kbe_serverlog (heartbeatTime, logger) values(1524988575,4000) ON DUPLICATE KEY UPDATE heartbeatTime=1524988575)
  INFO root [2018-04-29 15:56:16,197] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:16,197] - DBTask::process(): took 1.05 seconds
sql:(delete from kbe_entitylog where logger in (4000))
  INFO root [2018-04-29 15:56:16,236] - DBInterfaceMysql::query: successfully!
  INFO root [2018-04-29 15:56:16,237] - DBInterfaceMysql::query: successfully!
  INFO root [2018-04-29 15:56:16,238] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:16,238] - DBTask::process(): took 1.09 seconds
sql:(delete from kbe_email_verification where logtime<1524984976 and type=3)
  INFO root [2018-04-29 15:56:16,602] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:16,603] - DBTask::process(): took 1.46 seconds
sql:(show index from tbl_Account)
 DEBUG root [2018-04-29 15:56:16,615] - DBInterfaceMysql::dropEntityTableFromDB: tbl_Avatar.
  INFO root [2018-04-29 15:56:16,752] - DBInterfaceMysql::query: successfully!
 DEBUG root [2018-04-29 15:56:16,753] - DBInterfaceMysql::dropEntityTableFromDB: tbl_Energy.
  INFO root [2018-04-29 15:56:16,881] - DBInterfaceMysql::query: successfully!
 DEBUG root [2018-04-29 15:56:16,881] - DBInterfaceMysql::dropEntityTableFromDB: tbl_Halls.
  INFO root [2018-04-29 15:56:17,083] - DBInterfaceMysql::query: successfully!
 DEBUG root [2018-04-29 15:56:17,084] - DBInterfaceMysql::dropEntityTableFromDB: tbl_Room.
  INFO root [2018-04-29 15:56:17,197] - DBInterfaceMysql::query: successfully!
 DEBUG root [2018-04-29 15:56:17,198] - DBInterfaceMysql::dropEntityTableFromDB: tbl_judge.
  INFO root [2018-04-29 15:56:17,302] - DBInterfaceMysql::query: successfully!
  WARN root [2018-04-29 15:56:17,303] - e:\kbengine\kbe\src\server\dbmgr\dbmgr.cpp:275: Profile scriptCall took 3.78 seconds
  INFO root [2018-04-29 15:56:17,622] - ---- dbmgr is running ----
 DEBUG root [2018-04-29 15:56:17,622] - Components::process(): Request for the process of identity...
  INFO root [2018-04-29 15:56:24,404] - ServerApp::onRegisterNewApp: uid:21461, username:, componentType:baseappmgr, componentID:5000, globalorderID=-1, grouporderID=-1, intaddr:192.168.0.106, intport:51792, extaddr:nonsupport, extport:0,  from 192.168.0.106:51813/0/0/0.
  INFO root [2018-04-29 15:56:24,405] - Components::addComponent: reset orderLog, uid=21461!
  INFO root [2018-04-29 15:56:24,405] - Components::addComponent[baseappmgr], uid=21461, componentID=5000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-29 15:56:24,724] - Components::findComponents: find logger(1)...
  INFO root [2018-04-29 15:56:24,736] - Components::findComponents: found logger, addr:192.168.0.106:51799
  INFO root [2018-04-29 15:56:24,737] - Components::addComponent[logger], uid=21461, componentID=2000, globalorderid=2, grouporderid=1, totalcount=1
  INFO root [2018-04-29 15:56:24,744] - Components::process(): Found all the components!
  WARN root [2018-04-29 15:56:24,799] - Forwarding logs to logger[192.168.0.106:51799/0/0/0]...
 ERROR root [2018-04-29 15:56:34,324] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-29 15:56:34,347] - The following logs sent to logger failed:
  WARN root [2018-04-29 15:56:34,347] - ==> [2018-04-29 15:56:34 319] TCPPacketReceiver::processPendingEvents(192.168.0.106:51799): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-29 15:56:34,347] - ==> [2018-04-29 15:56:34 324] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
