  INFO root [2018-05-06 13:45:25,542] - 
  INFO root [2018-05-06 13:45:25,571] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:45:26,440] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:45:26,441] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:45:26,442] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:45:27,001] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:45:27,038] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:45:27,040] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50283 )
  INFO root [2018-05-06 13:45:27,040] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50283, SOMAXCONN=128.
  INFO root [2018-05-06 13:45:27,040] - server-configs:
  INFO root [2018-05-06 13:45:27,040] - 	internalAddr : 192.168.0.106:50283
  INFO root [2018-05-06 13:45:27,041] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:45:27,041] - 	componentID : 9000
  INFO root [2018-05-06 13:45:27,673] - Components::findLogger: found logger, addr:192.168.0.106:50274
  INFO root [2018-05-06 13:45:27,673] - Components::addComponent: reset orderLog, uid=4706!
  INFO root [2018-05-06 13:45:27,674] - Components::addComponent[logger], uid=4706, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:45:27,884] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 4706. PID: 4204 ----
  INFO root [2018-05-06 13:45:27,885] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:45:27,924] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:45:27,972] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:45:32,762] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:45:32,967] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:45:33,012] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:45:34,521] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:45:34,789] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:45:34,952] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:45:35,071] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:45:35,868] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:45:38,197] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:45:38,198] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:45:38,461] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:45:38,462] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:45:38,924] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:45:38,925] - Components::process(): Request for the process of identity...
  WARN root [2018-05-06 13:45:45,140] - Forwarding logs to logger[192.168.0.106:50274/0/0/0]...
 ERROR root [2018-05-06 13:46:05,862] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:46:05,871] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:46:05,871] - ==> [2018-05-06 13:46:05 859] TCPPacketReceiver::processPendingEvents(192.168.0.106:50274): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:46:05,871] - ==> [2018-05-06 13:46:05 863] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-06 13:46:05,916] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50277): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:46:05,918] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:46:05,926] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-06 13:46:05,927] - onLoginAppShutDown()
  INFO root [2018-05-06 13:46:05,927] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-06 13:46:05,927] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-06 13:46:05,927] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:46:05,927] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:46:05,927] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:46:05,928] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:46:05,928] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:46:05,928] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:46:05,928] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:46:05,928] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:46:05,952] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-06 13:46:05,952] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-06 13:46:07,112] - 
  INFO root [2018-05-06 13:46:07,115] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:46:07,116] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:46:07,116] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:46:07,116] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:46:07,126] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:46:07,126] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:46:07,130] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50313 )
  INFO root [2018-05-06 13:46:07,130] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50313, SOMAXCONN=128.
  INFO root [2018-05-06 13:46:07,130] - server-configs:
  INFO root [2018-05-06 13:46:07,131] - 	internalAddr : 192.168.0.106:50313
  INFO root [2018-05-06 13:46:07,131] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:46:07,131] - 	componentID : 9000
  INFO root [2018-05-06 13:46:08,818] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 4915. PID: 11184 ----
  INFO root [2018-05-06 13:46:08,819] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:46:08,819] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:46:08,819] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:46:08,942] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:46:08,942] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:46:08,943] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:46:08,946] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:46:08,946] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:46:08,946] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:46:08,946] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:46:08,974] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:46:09,001] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:46:09,001] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:46:09,003] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:46:09,003] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:46:09,288] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:46:09,289] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 13:46:16,420] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:46:16,461] - Components::findComponents: found logger, addr:192.168.0.106:50316
  INFO root [2018-05-06 13:46:16,462] - Components::addComponent: reset orderLog, uid=4915!
  INFO root [2018-05-06 13:46:16,462] - Components::addComponent[logger], uid=4915, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:46:16,463] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-06 13:46:16,565] - Components::findComponents: found dbmgr, addr:192.168.0.106:50310
  INFO root [2018-05-06 13:46:16,566] - Components::addComponent: reset orderLog, uid=4915!
  INFO root [2018-05-06 13:46:16,566] - Components::addComponent[dbmgr], uid=4915, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:46:16,566] - Components::findComponents: found dbmgr, addr:192.168.0.106:50310
  WARN root [2018-05-06 13:46:17,566] - Forwarding logs to logger[192.168.0.106:50316/0/0/0]...
 ERROR root [2018-05-06 13:51:34,946] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:51:34,955] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:51:34,955] - ==> [2018-05-06 13:51:34 945] TCPPacketReceiver::processPendingEvents(192.168.0.106:50316): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:51:34,955] - ==> [2018-05-06 13:51:34 947] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-06 13:51:35,005] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50310): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:51:35,007] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:51:35,012] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-06 13:51:35,014] - onLoginAppShutDown()
  INFO root [2018-05-06 13:51:35,014] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-06 13:51:35,014] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-06 13:51:35,014] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:51:35,014] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:51:35,014] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:51:35,015] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:51:35,015] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:51:35,015] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:51:35,015] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:51:35,015] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:51:35,023] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-06 13:51:35,023] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-06 13:51:36,123] - 
  INFO root [2018-05-06 13:51:36,123] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:51:36,124] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:51:36,124] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:51:36,124] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:51:36,127] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:51:36,127] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:51:36,128] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50404 )
  INFO root [2018-05-06 13:51:36,128] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50404, SOMAXCONN=128.
  INFO root [2018-05-06 13:51:36,128] - server-configs:
  INFO root [2018-05-06 13:51:36,128] - 	internalAddr : 192.168.0.106:50404
  INFO root [2018-05-06 13:51:36,128] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:51:36,128] - 	componentID : 9000
  INFO root [2018-05-06 13:51:37,819] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 5989. PID: 10972 ----
  INFO root [2018-05-06 13:51:37,820] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:51:37,820] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:51:37,820] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:51:37,947] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:51:37,947] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:51:37,948] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:51:37,951] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:51:37,952] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:51:37,952] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:51:37,953] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:51:37,985] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:51:38,018] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:51:38,018] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:51:38,020] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:51:38,020] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:51:38,354] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:51:38,355] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 13:51:45,441] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:51:45,489] - Components::findComponents: found logger, addr:192.168.0.106:50400
  INFO root [2018-05-06 13:51:45,489] - Components::addComponent: reset orderLog, uid=5989!
  INFO root [2018-05-06 13:51:45,490] - Components::addComponent[logger], uid=5989, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:51:45,491] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-06 13:51:46,591] - Forwarding logs to logger[192.168.0.106:50400/0/0/0]...
  INFO root [2018-05-06 13:51:51,562] - 
  INFO root [2018-05-06 13:51:51,562] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:51:51,563] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:51:51,563] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:51:51,563] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:51:51,565] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:51:51,565] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:51:51,567] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50431 )
  INFO root [2018-05-06 13:51:51,567] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50431, SOMAXCONN=128.
  INFO root [2018-05-06 13:51:51,567] - server-configs:
  INFO root [2018-05-06 13:51:51,567] - 	internalAddr : 192.168.0.106:50431
  INFO root [2018-05-06 13:51:51,567] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:51:51,567] - 	componentID : 9000
  INFO root [2018-05-06 13:51:53,261] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 6042. PID: 2476 ----
  INFO root [2018-05-06 13:51:53,261] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:51:53,262] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:51:53,262] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:51:53,396] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:51:53,396] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:51:53,397] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:51:53,401] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:51:53,401] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:51:53,401] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:51:53,402] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:51:53,442] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:51:53,476] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:51:53,476] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:51:53,478] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:51:53,478] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:51:53,807] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:51:53,807] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 13:52:00,899] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:52:00,935] - Components::findComponents: found logger, addr:192.168.0.106:50428
  INFO root [2018-05-06 13:52:00,935] - Components::addComponent: reset orderLog, uid=6042!
  INFO root [2018-05-06 13:52:00,936] - Components::addComponent[logger], uid=6042, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:52:00,940] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-06 13:52:02,049] - Forwarding logs to logger[192.168.0.106:50428/0/0/0]...
 ERROR root [2018-05-06 13:52:04,495] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:52:04,502] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:52:04,502] - ==> [2018-05-06 13:52:04 494] TCPPacketReceiver::processPendingEvents(192.168.0.106:50428): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:52:04,502] - ==> [2018-05-06 13:52:04 495] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:52:05,647] - 
  INFO root [2018-05-06 13:52:05,647] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:52:05,648] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:52:05,648] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:52:05,648] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:52:05,650] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:52:05,651] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:52:05,652] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50452 )
  INFO root [2018-05-06 13:52:05,652] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50452, SOMAXCONN=128.
  INFO root [2018-05-06 13:52:05,652] - server-configs:
  INFO root [2018-05-06 13:52:05,652] - 	internalAddr : 192.168.0.106:50452
  INFO root [2018-05-06 13:52:05,652] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:52:05,652] - 	componentID : 9000
  INFO root [2018-05-06 13:52:07,374] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 6087. PID: 9236 ----
  INFO root [2018-05-06 13:52:07,374] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:52:07,374] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:52:07,375] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:52:07,506] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:52:07,507] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:52:07,508] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:52:07,512] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:52:07,513] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:52:07,513] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:52:07,514] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:52:07,551] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:52:07,587] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:52:07,587] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:52:07,589] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:52:07,589] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:52:07,909] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:52:07,909] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 13:52:15,029] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:52:15,072] - Components::findComponents: found logger, addr:192.168.0.106:50447
  INFO root [2018-05-06 13:52:15,072] - Components::addComponent: reset orderLog, uid=6087!
  INFO root [2018-05-06 13:52:15,072] - Components::addComponent[logger], uid=6087, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:52:15,073] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-06 13:52:16,180] - Forwarding logs to logger[192.168.0.106:50447/0/0/0]...
 ERROR root [2018-05-06 13:52:42,211] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:52:42,214] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:52:42,214] - ==> [2018-05-06 13:52:42 211] TCPPacketReceiver::processPendingEvents(192.168.0.106:50447): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:52:42,214] - ==> [2018-05-06 13:52:42 212] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:53:15,836] - 
  INFO root [2018-05-06 13:53:15,836] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:53:15,837] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:53:15,837] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:53:15,837] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:53:15,839] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:53:15,839] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:53:15,840] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50521 )
  INFO root [2018-05-06 13:53:15,840] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50521, SOMAXCONN=128.
  INFO root [2018-05-06 13:53:15,840] - server-configs:
  INFO root [2018-05-06 13:53:15,841] - 	internalAddr : 192.168.0.106:50521
  INFO root [2018-05-06 13:53:15,841] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:53:15,841] - 	componentID : 9000
  INFO root [2018-05-06 13:53:17,539] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 6316. PID: 11300 ----
  INFO root [2018-05-06 13:53:17,540] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:53:17,540] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:53:17,540] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:53:17,664] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:53:17,664] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:53:17,665] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:53:17,669] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:53:17,669] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:53:17,669] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:53:17,670] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:53:17,707] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:53:17,737] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:53:17,737] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:53:17,739] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:53:17,739] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:53:18,066] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:53:18,066] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 13:53:25,139] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:53:25,230] - Components::findComponents: found logger, addr:192.168.0.106:50515
  INFO root [2018-05-06 13:53:25,230] - Components::addComponent: reset orderLog, uid=6316!
  INFO root [2018-05-06 13:53:25,231] - Components::addComponent[logger], uid=6316, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:53:25,232] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-05-06 13:53:26,336] - Forwarding logs to logger[192.168.0.106:50515/0/0/0]...
 ERROR root [2018-05-06 13:54:14,285] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:54:14,293] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:54:14,293] - ==> [2018-05-06 13:54:14 281] TCPPacketReceiver::processPendingEvents(192.168.0.106:50515): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:54:14,293] - ==> [2018-05-06 13:54:14 285] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:56:01,789] - 
  INFO root [2018-05-06 13:56:01,790] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:56:01,791] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:56:01,791] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:56:01,791] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:56:01,793] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:56:01,793] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:56:01,794] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50589 )
  INFO root [2018-05-06 13:56:01,794] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50589, SOMAXCONN=128.
  INFO root [2018-05-06 13:56:01,795] - server-configs:
  INFO root [2018-05-06 13:56:01,795] - 	internalAddr : 192.168.0.106:50589
  INFO root [2018-05-06 13:56:01,795] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:56:01,795] - 	componentID : 9000
  WARN root [2018-05-06 13:56:02,331] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20636, errorno=10048
  INFO root [2018-05-06 13:56:02,334] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 6858. PID: 10804 ----
  INFO root [2018-05-06 13:56:02,335] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:56:02,335] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:56:02,335] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:56:02,458] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:56:02,458] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:56:02,458] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:56:02,461] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:56:02,461] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:56:02,461] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:56:02,462] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:56:02,488] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:56:02,514] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:56:02,514] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:56:02,516] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:56:02,516] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:56:02,787] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:56:02,787] - Components::process(): Request for the process of identity...
  WARN root [2018-05-06 13:56:06,126] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20248, errorno=10048
  INFO root [2018-05-06 13:56:10,237] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 13:56:10,287] - Components::findComponents: found logger, addr:192.168.0.106:50586
  INFO root [2018-05-06 13:56:10,287] - Components::addComponent: reset orderLog, uid=6858!
  INFO root [2018-05-06 13:56:10,287] - Components::addComponent[logger], uid=6858, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:56:10,288] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-06 13:56:10,392] - Components::findComponents: found dbmgr, addr:192.168.0.106:50585
  INFO root [2018-05-06 13:56:10,392] - Components::addComponent: reset orderLog, uid=6858!
  INFO root [2018-05-06 13:56:10,393] - Components::addComponent[dbmgr], uid=6858, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:56:10,393] - Components::findComponents: found dbmgr, addr:192.168.0.106:50585
  WARN root [2018-05-06 13:56:11,393] - Forwarding logs to logger[192.168.0.106:50586/0/0/0]...
 ERROR root [2018-05-06 13:56:42,786] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:56:42,797] - The following logs sent to logger failed:
  WARN root [2018-05-06 13:56:42,797] - ==> [2018-05-06 13:56:42 781] TCPPacketReceiver::processPendingEvents(192.168.0.106:50586): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:56:42,797] - ==> [2018-05-06 13:56:42 787] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-06 13:56:42,839] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50585): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 13:56:42,841] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 13:56:42,875] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-06 13:56:42,880] - onLoginAppShutDown()
  INFO root [2018-05-06 13:56:42,880] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-06 13:56:42,880] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-06 13:56:42,880] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:56:42,880] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:56:42,880] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:56:42,880] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:56:42,881] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:56:42,881] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:56:42,881] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:56:42,881] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:56:42,889] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-06 13:56:42,889] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-06 13:56:44,013] - 
  INFO root [2018-05-06 13:56:44,013] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 13:56:44,014] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 13:56:44,014] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 13:56:44,014] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 13:56:44,017] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 13:56:44,017] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 13:56:44,018] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50627 )
  INFO root [2018-05-06 13:56:44,019] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50627, SOMAXCONN=128.
  INFO root [2018-05-06 13:56:44,019] - server-configs:
  INFO root [2018-05-06 13:56:44,019] - 	internalAddr : 192.168.0.106:50627
  INFO root [2018-05-06 13:56:44,019] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 13:56:44,019] - 	componentID : 9000
  INFO root [2018-05-06 13:56:44,391] - Components::findLogger: found logger, addr:192.168.0.106:50625
  INFO root [2018-05-06 13:56:44,391] - Components::addComponent: reset orderLog, uid=6995!
  INFO root [2018-05-06 13:56:44,391] - Components::addComponent[logger], uid=6995, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 13:56:44,395] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 6995. PID: 10156 ----
  INFO root [2018-05-06 13:56:44,395] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 13:56:44,396] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 13:56:44,396] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 13:56:44,518] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 13:56:44,518] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 13:56:44,519] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 13:56:44,522] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 13:56:44,522] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 13:56:44,522] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 13:56:44,522] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 13:56:44,549] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 13:56:44,575] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 13:56:44,575] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 13:56:44,577] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 13:56:44,577] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 13:56:44,890] - ---- loginapp is running ----
 DEBUG root [2018-05-06 13:56:44,890] - Components::process(): Request for the process of identity...
  WARN root [2018-05-06 13:56:50,961] - Forwarding logs to logger[192.168.0.106:50625/0/0/0]...
 ERROR root [2018-05-06 14:06:40,557] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 14:06:40,559] - The following logs sent to logger failed:
  WARN root [2018-05-06 14:06:40,559] - ==> [2018-05-06 14:06:40 554] TCPPacketReceiver::processPendingEvents(192.168.0.106:50625): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 14:06:40,559] - ==> [2018-05-06 14:06:40 557] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-06 14:06:40,608] - TCPPacketReceiver::processPendingEvents(192.168.0.106:50621): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-06 14:06:40,611] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-06 14:06:40,614] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-06 14:06:40,616] - onLoginAppShutDown()
  INFO root [2018-05-06 14:06:40,616] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-06 14:06:40,617] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 14:06:40,617] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 14:06:40,618] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 14:06:40,626] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-06 14:06:40,626] - ThreadPool::destroy(): starting size 2.
  INFO root [2018-05-06 14:06:41,743] - 
  INFO root [2018-05-06 14:06:41,745] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-06 14:06:41,745] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-05-06 14:06:41,745] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-05-06 14:06:41,745] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-05-06 14:06:41,751] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-05-06 14:06:41,751] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-05-06 14:06:41,753] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:50828 )
  INFO root [2018-05-06 14:06:41,753] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:50828, SOMAXCONN=128.
  INFO root [2018-05-06 14:06:41,753] - server-configs:
  INFO root [2018-05-06 14:06:41,754] - 	internalAddr : 192.168.0.106:50828
  INFO root [2018-05-06 14:06:41,754] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-05-06 14:06:41,754] - 	componentID : 9000
  INFO root [2018-05-06 14:06:43,462] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 8948. PID: 11528 ----
  INFO root [2018-05-06 14:06:43,462] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-05-06 14:06:43,462] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-06 14:06:43,463] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-06 14:06:43,588] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-06 14:06:43,588] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-06 14:06:43,588] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-06 14:06:43,592] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-06 14:06:43,592] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-06 14:06:43,592] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-06 14:06:43,593] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-06 14:06:43,623] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-06 14:06:43,657] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-05-06 14:06:43,657] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-06 14:06:43,659] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-06 14:06:43,659] - TelnetServer server is running on port 31000
  INFO root [2018-05-06 14:06:43,992] - ---- loginapp is running ----
 DEBUG root [2018-05-06 14:06:43,992] - Components::process(): Request for the process of identity...
  INFO root [2018-05-06 14:06:51,099] - Components::findComponents: find logger(1)...
  INFO root [2018-05-06 14:06:51,112] - Components::findComponents: found logger, addr:192.168.0.106:50825
  INFO root [2018-05-06 14:06:51,112] - Components::addComponent: reset orderLog, uid=8948!
  INFO root [2018-05-06 14:06:51,112] - Components::addComponent[logger], uid=8948, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 14:06:51,113] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-06 14:06:51,213] - Components::findComponents: found dbmgr, addr:192.168.0.106:50822
  INFO root [2018-05-06 14:06:51,214] - Components::addComponent: reset orderLog, uid=8948!
  INFO root [2018-05-06 14:06:51,214] - Components::addComponent[dbmgr], uid=8948, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-06 14:06:51,214] - Components::findComponents: found dbmgr, addr:192.168.0.106:50822
  WARN root [2018-05-06 14:06:52,215] - Forwarding logs to logger[192.168.0.106:50825/0/0/0]...
