  INFO root [2018-04-30 20:07:18,354] - 
  INFO root [2018-04-30 20:07:18,355] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 20:07:18,355] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-04-30 20:07:18,355] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-04-30 20:07:18,356] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 20:07:18,364] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-04-30 20:07:18,364] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-04-30 20:07:18,365] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:55035 )
  INFO root [2018-04-30 20:07:18,366] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:55035, SOMAXCONN=128.
  INFO root [2018-04-30 20:07:18,366] - server-configs:
  INFO root [2018-04-30 20:07:18,366] - 	internalAddr : 192.168.0.106:55035
  INFO root [2018-04-30 20:07:18,366] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-04-30 20:07:18,366] - 	componentID : 9000
  INFO root [2018-04-30 20:07:20,041] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 25126. PID: 7464 ----
  INFO root [2018-04-30 20:07:20,041] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-04-30 20:07:20,042] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-30 20:07:20,042] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-30 20:07:20,172] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 20:07:20,173] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 20:07:20,173] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 20:07:20,178] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 20:07:20,178] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 20:07:20,178] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 20:07:20,179] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 20:07:20,208] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 20:07:20,249] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-04-30 20:07:20,249] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-30 20:07:20,252] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-30 20:07:20,252] - TelnetServer server is running on port 31000
  INFO root [2018-04-30 20:07:20,585] - ---- loginapp is running ----
 DEBUG root [2018-04-30 20:07:20,585] - Components::process(): Request for the process of identity...
  INFO root [2018-04-30 20:07:27,673] - Components::findComponents: find logger(1)...
  INFO root [2018-04-30 20:07:27,696] - Components::findComponents: found logger, addr:192.168.0.106:55039
  INFO root [2018-04-30 20:07:27,697] - Components::addComponent: reset orderLog, uid=25126!
  INFO root [2018-04-30 20:07:27,697] - Components::addComponent[logger], uid=25126, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:07:27,698] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-04-30 20:07:27,799] - Components::findComponents: found dbmgr, addr:192.168.0.106:55038
  INFO root [2018-04-30 20:07:27,799] - Components::addComponent: reset orderLog, uid=25126!
  INFO root [2018-04-30 20:07:27,799] - Components::addComponent[dbmgr], uid=25126, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:07:27,800] - Components::findComponents: found dbmgr, addr:192.168.0.106:55038
  WARN root [2018-04-30 20:07:28,800] - Forwarding logs to logger[192.168.0.106:55039/0/0/0]...
 ERROR root [2018-04-30 20:15:21,397] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 20:15:21,424] - The following logs sent to logger failed:
  WARN root [2018-04-30 20:15:21,425] - ==> [2018-04-30 20:15:21 392] TCPPacketReceiver::processPendingEvents(192.168.0.106:55039): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 20:15:21,425] - ==> [2018-04-30 20:15:21 397] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-04-30 20:15:21,481] - TCPPacketReceiver::processPendingEvents(192.168.0.106:55038): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 20:15:21,487] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 20:15:21,511] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-04-30 20:15:21,513] - onLoginAppShutDown()
  INFO root [2018-04-30 20:15:21,513] - Shutdowner::onShutdown: shutting down
  INFO root [2018-04-30 20:15:21,513] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 20:15:21,514] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 20:15:21,521] - Script::uninstall(): is successfully!
 DEBUG root [2018-04-30 20:15:21,521] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-04-30 20:15:21,822] - ThreadPool::destroy(): waiting for thread(2)[0x209288,0x209220,], try=1
  INFO root [2018-04-30 20:15:25,410] - 
  INFO root [2018-04-30 20:15:25,410] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 20:15:25,410] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-04-30 20:15:25,410] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-04-30 20:15:25,411] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 20:15:25,413] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-04-30 20:15:25,413] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-04-30 20:15:25,414] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:55191 )
  INFO root [2018-04-30 20:15:25,414] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:55191, SOMAXCONN=128.
  INFO root [2018-04-30 20:15:25,414] - server-configs:
  INFO root [2018-04-30 20:15:25,414] - 	internalAddr : 192.168.0.106:55191
  INFO root [2018-04-30 20:15:25,414] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-04-30 20:15:25,414] - 	componentID : 9000
  WARN root [2018-04-30 20:15:25,933] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20895, errorno=10048
  INFO root [2018-04-30 20:15:25,936] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26716. PID: 11708 ----
  INFO root [2018-04-30 20:15:25,936] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-04-30 20:15:25,937] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-30 20:15:25,937] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-30 20:15:26,067] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 20:15:26,067] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 20:15:26,067] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 20:15:26,070] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 20:15:26,071] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 20:15:26,071] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 20:15:26,071] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 20:15:26,103] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 20:15:26,139] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-04-30 20:15:26,139] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-30 20:15:26,141] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-30 20:15:26,142] - TelnetServer server is running on port 31000
  INFO root [2018-04-30 20:15:26,431] - ---- loginapp is running ----
 DEBUG root [2018-04-30 20:15:26,432] - Components::process(): Request for the process of identity...
  INFO root [2018-04-30 20:15:33,562] - Components::findComponents: find logger(1)...
  INFO root [2018-04-30 20:15:33,653] - Components::findComponents: found logger, addr:192.168.0.106:55188
  INFO root [2018-04-30 20:15:33,654] - Components::addComponent: reset orderLog, uid=26716!
  INFO root [2018-04-30 20:15:33,654] - Components::addComponent[logger], uid=26716, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:15:33,657] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-04-30 20:15:33,762] - Components::findComponents: found dbmgr, addr:192.168.0.106:55187
  INFO root [2018-04-30 20:15:33,763] - Components::addComponent: reset orderLog, uid=26716!
  INFO root [2018-04-30 20:15:33,763] - Components::addComponent[dbmgr], uid=26716, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:15:33,764] - Components::findComponents: found dbmgr, addr:192.168.0.106:55187
  WARN root [2018-04-30 20:15:34,764] - Forwarding logs to logger[192.168.0.106:55188/0/0/0]...
 ERROR root [2018-04-30 20:15:39,955] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 20:15:39,981] - The following logs sent to logger failed:
  WARN root [2018-04-30 20:15:39,981] - ==> [2018-04-30 20:15:39 950] TCPPacketReceiver::processPendingEvents(192.168.0.106:55188): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 20:15:39,982] - ==> [2018-04-30 20:15:39 955] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-04-30 20:15:40,035] - TCPPacketReceiver::processPendingEvents(192.168.0.106:55187): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 20:15:40,043] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 20:15:40,069] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-04-30 20:15:40,070] - onLoginAppShutDown()
  INFO root [2018-04-30 20:15:40,070] - Shutdowner::onShutdown: shutting down
  INFO root [2018-04-30 20:15:40,071] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 20:15:40,071] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 20:15:40,079] - Script::uninstall(): is successfully!
 DEBUG root [2018-04-30 20:15:40,080] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-04-30 20:15:40,381] - ThreadPool::destroy(): waiting for thread(2)[0x181b288,0x181b220,], try=1
  INFO root [2018-04-30 20:15:41,484] - 
  INFO root [2018-04-30 20:15:41,485] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 20:15:41,485] - Resmgr::initialize: KBE_ROOT=E:/kbengine/
  INFO root [2018-04-30 20:15:41,485] - Resmgr::initialize: KBE_RES_PATH=E:/kbengine/kbe/res/;E:/kbengine/assets/;E:/kbengine/assets/scripts/;E:/kbengine/assets/res/
  INFO root [2018-04-30 20:15:41,485] - Resmgr::initialize: KBE_BIN_PATH=E:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 20:15:41,488] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:20013 )
  INFO root [2018-04-30 20:15:41,488] - NetworkInterface::initialize(EXTERNAL): address 192.168.0.106:20013, SOMAXCONN=128.
  INFO root [2018-04-30 20:15:41,491] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 192.168.0.106 ( 192.168.0.106:55221 )
  INFO root [2018-04-30 20:15:41,491] - NetworkInterface::initialize(INTERNAL): address 192.168.0.106:55221, SOMAXCONN=128.
  INFO root [2018-04-30 20:15:41,491] - server-configs:
  INFO root [2018-04-30 20:15:41,491] - 	internalAddr : 192.168.0.106:55221
  INFO root [2018-04-30 20:15:41,491] - 	externalAddr : 192.168.0.106:20013
  INFO root [2018-04-30 20:15:41,491] - 	componentID : 9000
  INFO root [2018-04-30 20:15:43,198] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 15:53:07 Apr 29 2018. AppID: 9000. UID: 26768. PID: 2240 ----
  INFO root [2018-04-30 20:15:43,198] - Server : Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz with 4194303kB RAM
  INFO root [2018-04-30 20:15:43,199] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-30 20:15:43,199] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-30 20:15:43,336] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 20:15:43,337] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 20:15:43,337] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 20:15:43,340] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 20:15:43,341] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 20:15:43,341] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 20:15:43,342] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 20:15:43,378] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 20:15:43,413] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 29 2018, 15:53:05) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-04-30 20:15:43,413] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-30 20:15:43,416] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-30 20:15:43,416] - TelnetServer server is running on port 31000
  INFO root [2018-04-30 20:15:43,713] - ---- loginapp is running ----
 DEBUG root [2018-04-30 20:15:43,713] - Components::process(): Request for the process of identity...
  INFO root [2018-04-30 20:15:50,816] - Components::findComponents: find logger(1)...
  INFO root [2018-04-30 20:15:50,894] - Components::findComponents: found logger, addr:192.168.0.106:55219
  INFO root [2018-04-30 20:15:50,895] - Components::addComponent: reset orderLog, uid=26768!
  INFO root [2018-04-30 20:15:50,895] - Components::addComponent[logger], uid=26768, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:15:50,896] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-04-30 20:15:50,998] - Components::findComponents: found dbmgr, addr:192.168.0.106:55220
  INFO root [2018-04-30 20:15:50,999] - Components::addComponent: reset orderLog, uid=26768!
  INFO root [2018-04-30 20:15:50,999] - Components::addComponent[dbmgr], uid=26768, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 20:15:50,999] - Components::findComponents: found dbmgr, addr:192.168.0.106:55220
  WARN root [2018-04-30 20:15:51,999] - Forwarding logs to logger[192.168.0.106:55219/0/0/0]...
